modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="${modGithub}/issues?q=is%3Aissue"
license="MIT"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
#updateJSONURL=""
displayURL="${curseHomepageUrl}"
logoFile="logo.png"
authors="${modAuthor}"
#credits=""
description='''${modDescription}'''

[[dependencies.ownshops]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraftVersionRange}"
    side="BOTH"
[[dependencies.ownshops]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersionRange}"
    side="BOTH"

